version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REPO
      - run: docker build -t $DOCKER_REPO/grpc-scala-fs2-publisher:$CIRCLE_BRANCH .
      - run:
          name: Publishing docker image
          command: |
            docker push $DOCKER_REPO/grpc-scala-fs2-publisher:$CIRCLE_BRANCH
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $DOCKER_REPO/grpc-scala-fs2-publisher:$CIRCLE_BRANCH $DOCKER_REPO/grpc-scala-fs2-publisher:latest
              docker push $DOCKER_REPO/grpc-scala-fs2-publisher:latest
            fi